package denoglobals

import (
	"reflect"
	"testing"
)

func TestParseShim(t *testing.T) {
	tests := []struct {
		name      string
		shimName  string
		content   string
		wantSpec  string
		wantFlags []string
		wantOK    bool
	}{
		{
			name:     "jsr specifier with permission flags (config stripped)",
			shimName: "serve",
			content: "#!/bin/sh\n# generated by deno install\n" +
				"exec deno run --allow-read --allow-net --config /home/u/.deno/bin/.serve/deno.json 'jsr:@std/http/file-server' \"$@\"\n",
			wantSpec:  "jsr:@std/http/file-server",
			wantFlags: []string{"--allow-read", "--allow-net"},
			wantOK:    true,
		},
		{
			name:     "npm specifier, only generated config flag",
			shimName: "cowsay",
			content: "#!/bin/sh\n# generated by deno install\n" +
				"exec deno run --config /home/u/.deno/bin/.cowsay/deno.json 'npm:cowsay' \"$@\"\n",
			wantSpec:  "npm:cowsay",
			wantFlags: []string{},
			wantOK:    true,
		},
		{
			name:     "url specifier no flags",
			shimName: "cat",
			content:  "#!/bin/sh\nexec deno run 'https://deno.land/std/examples/cat.ts' \"$@\"\n",
			wantSpec: "https://deno.land/std/examples/cat.ts",
			wantOK:   true,
		},
		{
			name:      "import-map generated flag is stripped too",
			shimName:  "tool",
			content:   "exec deno run --allow-all --import-map /x/import_map.json 'npm:tool' \"$@\"\n",
			wantSpec:  "npm:tool",
			wantFlags: []string{"--allow-all"},
			wantOK:    true,
		},
		{
			name:     "not a deno shim",
			shimName: "random",
			content:  "#!/bin/sh\necho hello\n",
			wantOK:   false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := parseShim(tt.shimName, tt.content)
			if ok != tt.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tt.wantOK)
			}
			if !tt.wantOK {
				return
			}
			if got.Name != tt.shimName {
				t.Errorf("Name = %q, want %q", got.Name, tt.shimName)
			}
			if got.Specifier != tt.wantSpec {
				t.Errorf("Specifier = %q, want %q", got.Specifier, tt.wantSpec)
			}
			if len(got.Flags) != 0 || len(tt.wantFlags) != 0 {
				if !reflect.DeepEqual(got.Flags, tt.wantFlags) {
					t.Errorf("Flags = %v, want %v", got.Flags, tt.wantFlags)
				}
			}
		})
	}
}
