package denoglobals

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sailingsam/pitara/internal/executil"
	"github.com/sailingsam/pitara/internal/plugins"
	"github.com/sailingsam/pitara/internal/snapshot"
)

type Plugin struct{}

func New() *Plugin { return &Plugin{} }

func (p *Plugin) Name() string { return "deno-globals" }

func (p *Plugin) Dependencies() []string { return []string{"deno"} }

func (p *Plugin) SupportedOS() []plugins.OS {
	// Windows shims use a different (.cmd) format — handle Unix first.
	return []plugins.OS{plugins.OSDarwin, plugins.OSLinux}
}

func (p *Plugin) Scan(ctx context.Context) (plugins.ScanResult, error) {
	result := plugins.ScanResult{PluginName: p.Name()}

	dir := denoBinDir()
	entries, err := os.ReadDir(dir)
	if err != nil {
		// No bin dir means nothing installed globally — not an error.
		result.Data, _ = marshalDeno(emptyGlobals())
		return result, nil
	}

	globals := make([]snapshot.DenoGlobal, 0, len(entries))
	for _, entry := range entries {
		// `deno install -g` drops a config dir like ".serve/" next to each
		// shim — skip directories and dot-entries, keep only the shims.
		if entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}
		g, ok := parseShim(entry.Name(), string(content))
		if !ok || plugins.IsSelf(g.Name) {
			continue
		}
		globals = append(globals, g)
	}

	data, err := marshalDeno(&snapshot.DenoGlobals{Globals: globals})
	if err != nil {
		return result, err
	}
	result.Data = data
	return result, nil
}

func (p *Plugin) Restore(ctx context.Context, snap json.RawMessage, opts plugins.RestoreOptions) (plugins.RestoreResult, error) {
	result := plugins.RestoreResult{PluginName: p.Name()}

	var payload struct {
		Deno *snapshot.DenoGlobals `json:"deno"`
	}
	if err := json.Unmarshal(snap, &payload); err != nil {
		result.Status = plugins.StatusFailed
		result.Message = "invalid deno snapshot data"
		return result, err
	}
	if payload.Deno == nil || len(payload.Deno.Globals) == 0 {
		result.Status = plugins.StatusSkipped
		result.Message = "no deno global packages in snapshot"
		return result, nil
	}

	if !executil.Available("deno") && !opts.DryRun {
		result.Status = plugins.StatusFailed
		result.Message = "deno not available"
		return result, fmt.Errorf("deno not available")
	}

	var failed int
	for _, g := range payload.Deno.Globals {
		args := append([]string{"install", "-g", "-f", "-n", g.Name}, g.Flags...)
		args = append(args, g.Specifier)

		if opts.DryRun {
			result.Details = append(result.Details, fmt.Sprintf("→ deno: %s (%s)", g.Name, g.Specifier))
			continue
		}

		if _, err := executil.Run(ctx, "deno", args...); err != nil {
			failed++
			result.Details = append(result.Details, fmt.Sprintf("✗ deno: %s — %s", g.Name, err.Error()))
			continue
		}
		result.Details = append(result.Details, fmt.Sprintf("✓ deno: %s", g.Name))
	}

	if opts.DryRun {
		result.Status = plugins.StatusSuccess
		result.Message = fmt.Sprintf("would install %d deno global CLI(s)", len(payload.Deno.Globals))
		return result, nil
	}

	if failed > 0 {
		result.Status = plugins.StatusFailed
		result.Message = fmt.Sprintf("%d of %d deno CLIs failed", failed, len(payload.Deno.Globals))
		return result, fmt.Errorf("%d deno CLI(s) failed", failed)
	}

	result.Status = plugins.StatusSuccess
	result.Message = fmt.Sprintf("restored %d deno global CLI(s)", len(payload.Deno.Globals))
	return result, nil
}

func marshalDeno(g *snapshot.DenoGlobals) (json.RawMessage, error) {
	return json.Marshal(struct {
		Deno *snapshot.DenoGlobals `json:"deno"`
	}{Deno: g})
}

func emptyGlobals() *snapshot.DenoGlobals {
	return &snapshot.DenoGlobals{Globals: []snapshot.DenoGlobal{}}
}

// denoBinDir returns where `deno install -g` places shims: $DENO_INSTALL_ROOT/bin
// if set, else ~/.deno/bin.
func denoBinDir() string {
	if root := os.Getenv("DENO_INSTALL_ROOT"); root != "" {
		return filepath.Join(root, "bin")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".deno", "bin")
}

// generated path-flags that `deno install` writes itself — they point at
// machine-specific files and must NOT be carried into the restore command.
var generatedFlags = map[string]bool{
	"--config":     true,
	"--import-map": true,
	"--lock":       true,
}

// parseShim extracts the module specifier and user permission flags from a
// Unix deno-install shim. A shim looks like:
//
//	#!/bin/sh
//	# generated by deno install
//	exec deno run --allow-read --allow-net --config /path/.serve/deno.json 'jsr:@std/http/file-server' "$@"
//
// name is the shim's filename (the `-n` install name).
func parseShim(name, content string) (snapshot.DenoGlobal, bool) {
	const marker = "exec deno run"

	var line string
	for _, l := range strings.Split(content, "\n") {
		if strings.Contains(l, marker) {
			line = l
			break
		}
	}
	if line == "" {
		return snapshot.DenoGlobal{}, false
	}

	rest := strings.TrimSpace(line[strings.Index(line, marker)+len(marker):])
	rest = strings.TrimSpace(strings.TrimSuffix(rest, `"$@"`))

	// The specifier is single-quoted; everything before it is flags.
	var specifier string
	if q1 := strings.Index(rest, "'"); q1 != -1 {
		if q2 := strings.Index(rest[q1+1:], "'"); q2 != -1 {
			specifier = rest[q1+1 : q1+1+q2]
			rest = strings.TrimSpace(rest[:q1])
		}
	}

	toks := strings.Fields(rest)
	if specifier == "" && len(toks) > 0 {
		// Fallback: unquoted specifier is the last token.
		specifier = strings.Trim(toks[len(toks)-1], "'\"")
		toks = toks[:len(toks)-1]
	}
	if specifier == "" {
		return snapshot.DenoGlobal{}, false
	}

	flags := make([]string, 0, len(toks))
	for i := 0; i < len(toks); i++ {
		t := toks[i]
		if generatedFlags[t] {
			i++ // also skip the flag's value token
			continue
		}
		if eq := strings.Index(t, "="); eq != -1 && generatedFlags[t[:eq]] {
			continue
		}
		flags = append(flags, t)
	}

	return snapshot.DenoGlobal{Name: name, Specifier: specifier, Flags: flags}, true
}
